version: "3.7"
services:
  api:
    build:
      args:
        user: lucas
        uid: 1000
      context: ./API
      dockerfile: Dockerfile
    image: api
    container_name: api-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./API/app:/var/www
    networks:
      - travellist
  
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./FrontEnd/app:/app
    networks:
      - travellist

  db:
    image: mysql:8.0
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - travellist

networks:
  travellist:
    driver: bridge